version: '3.8'

services:
    laravel.test:
        build:
            context: .
        user: root
        ports:
            - '80:80'  # Map internal port 80 to host port 80
        depends_on:
            - mariadb
        networks:
            - sail

    mariadb:
        image: 'mariadb:11'
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_HOST: '%'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        volumes:
            - 'sail-mariadb:/var/lib/mysql'
            - './vendor/laravel/sail/database/mariadb/create-testing-database.sh:/docker-entrypoint-initdb.d/10-create-testing-database.sh'
            - './local-database:/var/lib/mysql'  # Add this line to mount a local volume for the database
        networks:
            - sail
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}"]
            retries: 3
            timeout: 5s

    phpmyadmin:
        image: phpmyadmin:latest
        ports:
            - '8080:80'  # Access phpMyAdmin on http://localhost:8080
        environment:
            PMA_HOST: mariadb  # Links phpMyAdmin to your MariaDB container
            PMA_PORT: 3306
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'  # Use the root password for access
        depends_on:
            - mariadb
        networks:
            - sail

networks:
    sail:
        driver: bridge

volumes:
    sail-mariadb:
        driver: local